# For more info on HTTP files go to https://aka.ms/vs/httpfile

### Test Case 1

GET http://localhost:7000/api/demo/test?case=1 HTTP/1.1

### Test Case 2

GET http://localhost:7000/api/demo/test?case=2 HTTP/1.1
